// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/orchestrator.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilliCpu      int64                  `protobuf:"varint,1,opt,name=milli_cpu,json=milliCpu,proto3" json:"milli_cpu,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRequest) GetMilliCpu() int64 {
	if x != nil {
		return x.MilliCpu
	}
	return 0
}

func (x *ResourceRequest) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type Toleration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Effect        string                 `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toleration) Reset() {
	*x = Toleration{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toleration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toleration) ProtoMessage() {}

func (x *Toleration) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toleration.ProtoReflect.Descriptor instead.
func (*Toleration) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *Toleration) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Toleration) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Toleration) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *Toleration) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type DeploymentSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image           string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullSecret string                 `protobuf:"bytes,8,opt,name=image_pull_secret,json=imagePullSecret,proto3" json:"image_pull_secret,omitempty"`
	Replicas        int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Resources       *ResourceRequest       `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tolerations     []*Toleration          `protobuf:"bytes,6,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	Priority        int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeploymentSpec) Reset() {
	*x = DeploymentSpec{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSpec) ProtoMessage() {}

func (x *DeploymentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSpec.ProtoReflect.Descriptor instead.
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeploymentSpec) GetImagePullSecret() string {
	if x != nil {
		return x.ImagePullSecret
	}
	return ""
}

func (x *DeploymentSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *DeploymentSpec) GetResources() *ResourceRequest {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DeploymentSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeploymentSpec) GetTolerations() []*Toleration {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *DeploymentSpec) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *DeploymentSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetSpec() *DeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *DeploymentSpec        `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentRequest) Reset() {
	*x = CreateDeploymentRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentRequest) ProtoMessage() {}

func (x *CreateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDeploymentRequest) GetSpec() *DeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentResponse) Reset() {
	*x = CreateDeploymentResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentResponse) ProtoMessage() {}

func (x *CreateDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentResponse.ProtoReflect.Descriptor instead.
func (*CreateDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDeploymentResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type DeleteDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeploymentRequest) Reset() {
	*x = DeleteDeploymentRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentRequest) ProtoMessage() {}

func (x *DeleteDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDeploymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeploymentResponse) Reset() {
	*x = DeleteDeploymentResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentResponse) ProtoMessage() {}

func (x *DeleteDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDeploymentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsRequest) Reset() {
	*x = ListDeploymentsRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsRequest) ProtoMessage() {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{8}
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *ListDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type ClusterNode struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AllocatableMilliCpu int64                  `protobuf:"varint,3,opt,name=allocatable_milli_cpu,json=allocatableMilliCpu,proto3" json:"allocatable_milli_cpu,omitempty"`
	AllocatableMemoryMb int64                  `protobuf:"varint,4,opt,name=allocatable_memory_mb,json=allocatableMemoryMb,proto3" json:"allocatable_memory_mb,omitempty"`
	UsedMilliCpu        int64                  `protobuf:"varint,5,opt,name=used_milli_cpu,json=usedMilliCpu,proto3" json:"used_milli_cpu,omitempty"`
	UsedMemoryMb        int64                  `protobuf:"varint,6,opt,name=used_memory_mb,json=usedMemoryMb,proto3" json:"used_memory_mb,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClusterNode) Reset() {
	*x = ClusterNode{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNode) ProtoMessage() {}

func (x *ClusterNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNode.ProtoReflect.Descriptor instead.
func (*ClusterNode) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterNode) GetAllocatableMilliCpu() int64 {
	if x != nil {
		return x.AllocatableMilliCpu
	}
	return 0
}

func (x *ClusterNode) GetAllocatableMemoryMb() int64 {
	if x != nil {
		return x.AllocatableMemoryMb
	}
	return 0
}

func (x *ClusterNode) GetUsedMilliCpu() int64 {
	if x != nil {
		return x.UsedMilliCpu
	}
	return 0
}

func (x *ClusterNode) GetUsedMemoryMb() int64 {
	if x != nil {
		return x.UsedMemoryMb
	}
	return 0
}

type ClusterStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStateRequest) Reset() {
	*x = ClusterStateRequest{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStateRequest) ProtoMessage() {}

func (x *ClusterStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStateRequest.ProtoReflect.Descriptor instead.
func (*ClusterStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{11}
}

type ClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ClusterNode         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStateResponse) Reset() {
	*x = ClusterStateResponse{}
	mi := &file_api_proto_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStateResponse) ProtoMessage() {}

func (x *ClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStateResponse.ProtoReflect.Descriptor instead.
func (*ClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *ClusterStateResponse) GetNodes() []*ClusterNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_api_proto_orchestrator_proto protoreflect.FileDescriptor

const file_api_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/orchestrator.proto\x12\x0forchestrator.v1\"K\n" +
	"\x0fResourceRequest\x12\x1b\n" +
	"\tmilli_cpu\x18\x01 \x01(\x03R\bmilliCpu\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\"h\n" +
	"\n" +
	"Toleration\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\"\x9d\x03\n" +
	"\x0eDeploymentSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12*\n" +
	"\x11image_pull_secret\x18\b \x01(\tR\x0fimagePullSecret\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12>\n" +
	"\tresources\x18\x04 \x01(\v2 .orchestrator.v1.ResourceRequestR\tresources\x12C\n" +
	"\x06labels\x18\x05 \x03(\v2+.orchestrator.v1.DeploymentSpec.LabelsEntryR\x06labels\x12=\n" +
	"\vtolerations\x18\x06 \x03(\v2\x1b.orchestrator.v1.TolerationR\vtolerations\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.orchestrator.v1.DeploymentSpecR\x04spec\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"N\n" +
	"\x17CreateDeploymentRequest\x123\n" +
	"\x04spec\x18\x01 \x01(\v2\x1f.orchestrator.v1.DeploymentSpecR\x04spec\"W\n" +
	"\x18CreateDeploymentResponse\x12;\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x1b.orchestrator.v1.DeploymentR\n" +
	"deployment\")\n" +
	"\x17DeleteDeploymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18DeleteDeploymentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x18\n" +
	"\x16ListDeploymentsRequest\"X\n" +
	"\x17ListDeploymentsResponse\x12=\n" +
	"\vdeployments\x18\x01 \x03(\v2\x1b.orchestrator.v1.DeploymentR\vdeployments\"\xe9\x01\n" +
	"\vClusterNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x122\n" +
	"\x15allocatable_milli_cpu\x18\x03 \x01(\x03R\x13allocatableMilliCpu\x122\n" +
	"\x15allocatable_memory_mb\x18\x04 \x01(\x03R\x13allocatableMemoryMb\x12$\n" +
	"\x0eused_milli_cpu\x18\x05 \x01(\x03R\fusedMilliCpu\x12$\n" +
	"\x0eused_memory_mb\x18\x06 \x01(\x03R\fusedMemoryMb\"\x15\n" +
	"\x13ClusterStateRequest\"J\n" +
	"\x14ClusterStateResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.orchestrator.v1.ClusterNodeR\x05nodes2\xad\x03\n" +
	"\x13OrchestratorService\x12g\n" +
	"\x10CreateDeployment\x12(.orchestrator.v1.CreateDeploymentRequest\x1a).orchestrator.v1.CreateDeploymentResponse\x12g\n" +
	"\x10DeleteDeployment\x12(.orchestrator.v1.DeleteDeploymentRequest\x1a).orchestrator.v1.DeleteDeploymentResponse\x12d\n" +
	"\x0fListDeployments\x12'.orchestrator.v1.ListDeploymentsRequest\x1a(.orchestrator.v1.ListDeploymentsResponse\x12^\n" +
	"\x0fGetClusterState\x12$.orchestrator.v1.ClusterStateRequest\x1a%.orchestrator.v1.ClusterStateResponseB.Z,minikube-orchestrator/internal/grpcpb;grpcpbb\x06proto3"

var (
	file_api_proto_orchestrator_proto_rawDescOnce sync.Once
	file_api_proto_orchestrator_proto_rawDescData []byte
)

func file_api_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_api_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_api_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)))
	})
	return file_api_proto_orchestrator_proto_rawDescData
}

var file_api_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_orchestrator_proto_goTypes = []any{
	(*ResourceRequest)(nil),          // 0: orchestrator.v1.ResourceRequest
	(*Toleration)(nil),               // 1: orchestrator.v1.Toleration
	(*DeploymentSpec)(nil),           // 2: orchestrator.v1.DeploymentSpec
	(*Deployment)(nil),               // 3: orchestrator.v1.Deployment
	(*CreateDeploymentRequest)(nil),  // 4: orchestrator.v1.CreateDeploymentRequest
	(*CreateDeploymentResponse)(nil), // 5: orchestrator.v1.CreateDeploymentResponse
	(*DeleteDeploymentRequest)(nil),  // 6: orchestrator.v1.DeleteDeploymentRequest
	(*DeleteDeploymentResponse)(nil), // 7: orchestrator.v1.DeleteDeploymentResponse
	(*ListDeploymentsRequest)(nil),   // 8: orchestrator.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),  // 9: orchestrator.v1.ListDeploymentsResponse
	(*ClusterNode)(nil),              // 10: orchestrator.v1.ClusterNode
	(*ClusterStateRequest)(nil),      // 11: orchestrator.v1.ClusterStateRequest
	(*ClusterStateResponse)(nil),     // 12: orchestrator.v1.ClusterStateResponse
	nil,                              // 13: orchestrator.v1.DeploymentSpec.LabelsEntry
}
var file_api_proto_orchestrator_proto_depIdxs = []int32{
	0,  // 0: orchestrator.v1.DeploymentSpec.resources:type_name -> orchestrator.v1.ResourceRequest
	13, // 1: orchestrator.v1.DeploymentSpec.labels:type_name -> orchestrator.v1.DeploymentSpec.LabelsEntry
	1,  // 2: orchestrator.v1.DeploymentSpec.tolerations:type_name -> orchestrator.v1.Toleration
	2,  // 3: orchestrator.v1.Deployment.spec:type_name -> orchestrator.v1.DeploymentSpec
	2,  // 4: orchestrator.v1.CreateDeploymentRequest.spec:type_name -> orchestrator.v1.DeploymentSpec
	3,  // 5: orchestrator.v1.CreateDeploymentResponse.deployment:type_name -> orchestrator.v1.Deployment
	3,  // 6: orchestrator.v1.ListDeploymentsResponse.deployments:type_name -> orchestrator.v1.Deployment
	10, // 7: orchestrator.v1.ClusterStateResponse.nodes:type_name -> orchestrator.v1.ClusterNode
	4,  // 8: orchestrator.v1.OrchestratorService.CreateDeployment:input_type -> orchestrator.v1.CreateDeploymentRequest
	6,  // 9: orchestrator.v1.OrchestratorService.DeleteDeployment:input_type -> orchestrator.v1.DeleteDeploymentRequest
	8,  // 10: orchestrator.v1.OrchestratorService.ListDeployments:input_type -> orchestrator.v1.ListDeploymentsRequest
	11, // 11: orchestrator.v1.OrchestratorService.GetClusterState:input_type -> orchestrator.v1.ClusterStateRequest
	5,  // 12: orchestrator.v1.OrchestratorService.CreateDeployment:output_type -> orchestrator.v1.CreateDeploymentResponse
	7,  // 13: orchestrator.v1.OrchestratorService.DeleteDeployment:output_type -> orchestrator.v1.DeleteDeploymentResponse
	9,  // 14: orchestrator.v1.OrchestratorService.ListDeployments:output_type -> orchestrator.v1.ListDeploymentsResponse
	12, // 15: orchestrator.v1.OrchestratorService.GetClusterState:output_type -> orchestrator.v1.ClusterStateResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_orchestrator_proto_init() }
func file_api_proto_orchestrator_proto_init() {
	if File_api_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_proto_rawDesc), len(file_api_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_api_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_api_proto_orchestrator_proto = out.File
	file_api_proto_orchestrator_proto_goTypes = nil
	file_api_proto_orchestrator_proto_depIdxs = nil
}
